In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as BS
import json
import seaborn as sns
import re
from IPython.core.display import HTML

In [2]:
orange = pd.read_csv('../data/orange_vrbo.csv')

In [3]:
orange = orange.drop(columns = {'data.results.listings.virtualTourBadge',
       'data.results.listings.listingId',
       'data.results.listings.detailPageUrl',
       'data.results.listings.instantBookable',
       'data.results.listings.listingNumber',
       'data.results.listings.propertyId',
        'data.results.filterGroups[0].groupInfo.__typename',
       'data.results.filterGroups[0].filters[0].count',
       'data.results.filterGroups[0].filters[0].checked',
       'data.results.filterGroups[0].filters[0].__typename',
       'data.results.filterGroups[0].filters[0].filter.id',
       'data.results.filterGroups[0].filters[0].filter.name',
       'data.results.filterGroups[0].filters[0].filter.refineByQueryArgument',
       'data.results.filterGroups[0].filters[0].filter.description',
       'data.results.filterGroups[0].filters[0].filter.__typename',
       'data.results.filterGroups[0].filters[0].filter.groupId'})

In [4]:
orange

,data.results.listings.bedrooms,data.results.listings.propertyType,data.results.listings.sleeps,data.results.listings.petsAllowed,data.results.listings.averageRating,data.results.listings.reviewCount,data.results.listings.minStayRange.minStayHigh,data.results.listings.minStayRange.minStayLow,data.results.listings.propertyMetadata.headline,data.results.listings.unitMetadata.unitName,...,data.results.parsedParams.dates.__typename,data.results.mapViewport.__typename,data.results.globalMessages.__typename,data.results.filterGroups[0].__typename,errors[0].message,errors[0].extensions.errorCode,errors[0].extensions.unit,errors[0].extensions.code,errors[0].locations[0].line,errors[0].locations[0].column
0,3,Condo,8,False,4.944445,90,7,7,"Designer Modern, DIRECT GULFRONT, Ground floo...",unit_409460,...,NaN,NaN,NaN,NaN,Could not retrieve priceSummary,NegativeRateError,9e9eb957-bd86-42b1-96ac-9b3b0e1d0d33,INTERNAL_SERVER_ERROR,170.0,3.0
1,2,Condo,4,False,5.000000,17,7,7,**BEACH CHAIR SERVICE INCLUDED WITH RENTAL!!**...,unit_3247441,...,NaN,NaN,NaN,NaN,Could not retrieve priceSummary,NegativeRateError,9e9eb957-bd86-42b1-96ac-9b3b0e1d0d33,INTERNAL_SERVER_ERROR,170.0,3.0
2,2,Condo,6,False,4.636363,22,3,3,"Seascape 210- CONVENIENT LOCATION, FUN FOR THE...",SeaScape 210,...,NaN,NaN,NaN,NaN,Could not retrieve priceSummary,NegativeRateError,9e9eb957-bd86-42b1-96ac-9b3b0e1d0d33,INTERNAL_SERVER_ERROR,170.0,3.0
3,3,Condo,6,False,4.958334,24,7,7,Luxurious Beachfront Unit | Stunning Gulf Vie...,unit_3157846,...,NaN,NaN,NaN,NaN,Could not retrieve priceSummary,NegativeRateError,9e9eb957-bd86-42b1-96ac-9b3b0e1d0d33,INTERNAL_SERVER_ERROR,170.0,3.0
4,2,Condo,8,False,4.789473,19,3,3,Upgraded Beachfront Condo | Private Balcony Vi...,Phoenix 7 Unit 215,...,NaN,NaN,NaN,NaN,Could not retrieve priceSummary,NegativeRateError,9e9eb957-bd86-42b1-96ac-9b3b0e1d0d33,INTERNAL_SERVER_ERROR,170.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,3,Condo,8,False,4.680000,25,2,2,"Great View! 3 bed 3 bath, Sleeps 8, Large Balc...",unit_2612045,...,SearchDateRange,MapViewport,GlobalMessages,SearchFilterGroup,NaN,NaN,NaN,NaN,NaN,NaN
346,4,Condo,10,False,4.837838,37,3,3,Spacious Beachfront Corner Condo | Resort Amen...,Escapes To The Shores Unit 1305,...,SearchDateRange,MapViewport,GlobalMessages,SearchFilterGroup,NaN,NaN,NaN,NaN,NaN,NaN
347,3,House,6,True,4.926471,136,4,3,"Quiet Neighborhood, 3 bedrooms, Equipped kitch...",unit_1132925,...,SearchDateRange,MapViewport,GlobalMessages,SearchFilterGroup,NaN,NaN,NaN,NaN,NaN,NaN
348,3,Condo,12,False,4.560000,25,3,3,Top of the Line! Great Three Bedroom Four Bat...,Phoenix West II 3009,...,SearchDateRange,MapViewport,GlobalMessages,SearchFilterGroup,NaN,NaN,NaN,NaN,NaN,NaN
349,1,Condo,6,False,4.920000,25,3,3,"Tradewinds #208 - Cozy Unit, Beachfront Comple...",Tradewinds 208,...,SearchDateRange,MapViewport,GlobalMessages,SearchFilterGroup,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
orange = orange.drop(columns = {'data.results.listings.__typename', 'data.results.listings.minStayRange.minStayHigh',
       'data.results.listings.minStayRange.minStayLow',
       'data.results.listings.minStayRange.__typename', 'data.results.mapViewport.neLong', 'data.results.mapViewport.swLat',
       'data.results.mapViewport.swLong',
       'data.results.mapViewport.__typename',
       'data.results.globalMessages.alert',
       'data.results.globalMessages.__typename',
       'data.results.globalMessages.banner',
       'data.results.filterGroups[0].__typename',
       'data.results.filterGroups[0].groupInfo.id',
       'data.results.filterGroups[0].groupInfo.name'})

In [6]:
orange = orange.drop(columns = {'data.results.parsedParams.coreFilters.minBathrooms',
       'data.results.parsedParams.coreFilters.maxBathrooms',
       'data.results.parsedParams.coreFilters.minNightlyPrice',
       'data.results.parsedParams.coreFilters.maxNightlyPrice',
       'data.results.parsedParams.coreFilters.minSleeps',
       'data.results.parsedParams.coreFilters.__typename',
       'data.results.parsedParams.dates.arrivalDate',
       'data.results.parsedParams.dates.departureDate',
       'data.results.parsedParams.dates.__typename',
       'data.results.mapViewport.neLat', 'data.results.listings.propertyMetadata.headline',
       'data.results.listings.propertyMetadata.__typename',
       'data.results.listings.unitMetadata.unitName',
       'data.results.listings.unitMetadata.__typename'})

In [7]:
orange = orange.drop(columns = {'data.results.listings.bathrooms.toiletOnly',
       'data.results.listings.bathrooms.__typename', 'data.results.percentBooked.currentPercentBooked',
       'data.results.percentBooked.__typename', 'data.results.parsedParams.q',
       'data.results.parsedParams.sort',
       'data.results.parsedParams.__typename',
       'data.results.parsedParams.coreFilters.adults',
       'data.results.parsedParams.coreFilters.children',
       'data.results.parsedParams.coreFilters.pets',
       'data.results.parsedParams.coreFilters.minBedrooms',
       'data.results.parsedParams.coreFilters.maxBedrooms'})

In [8]:
orange = orange.drop(columns = {'data.results.listings.spaces.__typename',
       'data.results.listings.spaces.spacesSummary.bedCountDisplay', 'data.results.destination.breadcrumbs[0].url',
       'data.results.destination.breadcrumbs[0].__typename',
       'data.results.destinationMessage.iconText',
       'data.results.destinationMessage.__typename',
       'data.results.destinationMessage.iconTitleText.title',
       'data.results.destinationMessage.iconTitleText.message',
       'data.results.destinationMessage.iconTitleText.icon',
       'data.results.destinationMessage.iconTitleText.messageValueType',
       'data.results.destinationMessage.iconTitleText.link',
       'data.results.destinationMessage.iconTitleText.__typename'})

In [9]:
orange = orange.rename(columns={'data.results.listings.bedrooms':'bedrooms', 'data.results.listings.propertyType':'type',
       'data.results.listings.sleeps':'sleeps', 'data.results.listings.petsAllowed':'pets_allowed',
       'data.results.listings.averageRating':'rating',
       'data.results.listings.reviewCount':'review_count',
       'data.results.listings.bathrooms.full':'full_bathrooms',
       'data.results.listings.bathrooms.half':'half_bathrooms'})

In [10]:
orange = orange.drop(columns={'data.results.listings.spaces.spacesSummary.__typename',
       'data.results.listings.spaces.spacesSummary.area.areaValue', 'data.results.geography.location.__typename',
       'data.results.geography.breadcrumbs[0].name',
       'data.results.geography.breadcrumbs[0].countryCode',
       'data.results.geography.breadcrumbs[0].primaryGeoType',
       'data.results.geography.breadcrumbs[0].__typename',
       'data.results.geography.breadcrumbs[0].location.latitude',
       'data.results.geography.breadcrumbs[0].location.longitude',
       'data.results.geography.breadcrumbs[0].location.__typename',
       'data.results.destination.__typename',
       'data.results.destination.breadcrumbs[0].name'})

In [11]:
orange = orange.drop(columns={'data.results.listings.spaces.spacesSummary.area.__typename',
       'data.results.listings.geoDistance.text',
       'data.results.listings.geoDistance.relationType',
       'data.results.listings.geoDistance.__typename', 'data.results.listings.priceSummary.edapEventJson',
        'data.results.propertyRedirectUrl', 'data.results.__typename',
       'data.results.resultCount', 'data.results.page',
       'data.results.pageSize', 'data.results.pageCount',
       'data.results.queryUUID', 'data.results.pinnedListing',
       'data.results.fromRecord', 'data.results.toRecord',
       'data.results.internalTools', 'data.results.typeaheadSuggestion.name',
       'data.results.typeaheadSuggestion.uuid',
       'data.results.typeaheadSuggestion.term',
       'data.results.typeaheadSuggestion.__typename',
       'data.results.geography.name', 'data.results.geography.lbsId',
       'data.results.geography.gaiaId', 'data.results.geography.isGeocoded',
       'data.results.geography.shouldShowMapCentralPin',
       'data.results.geography.__typename',
       'data.results.geography.description',
       'data.results.geography.primaryGeoType',
         'data.results.listings.prices.total.amount',
       'data.results.listings.prices.total.formattedAmount',
       'data.results.listings.prices.total.roundedFormattedAmount',
       'data.results.listings.prices.total.pricePeriodDescription',
       'data.results.listings.prices.total.__typename'})

In [12]:
orange = orange.drop(columns={'errors[0].extensions.errorCode', 'errors[0].extensions.unit',
       'errors[0].extensions.code', 'errors[0].locations[0].line',
       'errors[0].locations[0].column', 'data.results.listings.amenitiesBadges[0].id',
       'data.results.listings.amenitiesBadges[0].name',
       'data.results.listings.amenitiesBadges[0].helpText',
       'data.results.listings.images[0].altText',
       'data.results.listings.images[0].c6_uri',
       'data.results.listings.images[0].c9_uri',
       'data.results.listings.images[0].mab.banditId',
       'data.results.listings.images[0].mab.payloadId',
       'data.results.listings.images[0].mab.campaignId',
       'data.results.listings.images[0].mab.cached',
       'data.results.listings.images[0].mab.arm',
       'data.results.listings.images[0].mab',
       'data.results.listings.rankedBadges[0].id',
       'data.results.listings.rankedBadges[0].name',
       'data.results.listings.rankedBadges[0].helpText',
       'data.results.listings.superlativesBadges[0].id',
       'data.results.listings.superlativesBadges[0].name',
       'data.results.listings.superlativesBadges[0].helpText',
       'data.results.listings.virtualTourBadge.id',
       'data.results.listings.virtualTourBadge.name',
       'data.results.listings.virtualTourBadge.helpText',
       'data.results.listings.priceSummary',
       'data.results.listings.priceSummarySecondary',
       'data.results.listings.priceLabel', 'data.results.listings.prices',
       'data.results.listings.priceSummary.__typename',
       'data.results.listings.priceSummarySecondary.__typename',
       'data.results.listings.priceLabel.__typename',
       'data.results.listings.prices.__typename',
       'data.results.listings.prices.perNight.__typename',
       'data.results.listings.geoCode.__typename',
       'data.results.listings.amenitiesBadges[0].__typename',
       'data.results.listings.images[0].__typename',
       'data.results.listings.rankedBadges[0].__typename',
       'data.results.listings.superlativesBadges[0].__typename',
       'data.results.listings.virtualTourBadge.__typename',
       'data.results.listings.images[0].mab.__typename', 'data.results.id',
        'data.results.listings.prices.perNight.pricePeriodDescription'})

In [13]:
orange = orange.drop(columns={'data.results.geography.location.latitude',
       'data.results.geography.location.longitude', 'errors[0].message',
        'data.results.listings.priceSummary.pricePeriodDescription',
       'data.results.listings.priceSummarySecondary.priceTypeId',
       'data.results.listings.priceSummarySecondary.edapEventJson',
       'data.results.listings.priceSummarySecondary.formattedAmount',
       'data.results.listings.priceSummarySecondary.roundedFormattedAmount',
       'data.results.listings.priceSummarySecondary.pricePeriodDescription',
       'data.results.listings.priceLabel.priceTypeId',
       'data.results.listings.priceLabel.pricePeriodDescription',
       'data.results.listings.prices.label',
       'data.results.listings.prices.mainPrice',
       'data.results.listings.prices.perNight.amount',
       'data.results.listings.prices.perNight.formattedAmount'})

In [14]:
orange = orange.drop(columns={'data.results.listings.priceSummary.priceAccurate',
       'data.results.listings.priceSummary.priceTypeId',
       'data.results.listings.priceSummary.formattedAmount',
       'data.results.listings.priceSummary.roundedFormattedAmount'})

In [15]:
orange = orange.rename(columns = {'data.results.listings.prices.perNight.roundedFormattedAmount':'cost_night',
       'data.results.listings.geoCode.latitude':'lat',
       'data.results.listings.geoCode.longitude':'lon'})

In [16]:
orange['cost_night'] = orange['cost_night'].str.replace('$', '')

C:\Users\bswil\AppData\Local\Temp\ipykernel_9452\1484854898.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  orange['cost_night'] = orange['cost_night'].str.replace('$', '')

In [17]:
orange['cost_night'] = orange['cost_night'].str.replace(',', '')

In [18]:
orange = orange.drop(35)

In [19]:
orange['cost_night'] = orange['cost_night'].astype(int)

In [20]:
orange['half_bathrooms'] = orange['half_bathrooms']/2

In [21]:
orange['bathrooms'] = orange['full_bathrooms']+orange['half_bathrooms']

In [22]:
orange = orange.drop(columns={'full_bathrooms', 'half_bathrooms'})

In [23]:
orange

,bedrooms,type,sleeps,pets_allowed,rating,review_count,cost_night,lat,lon,bathrooms
0,3,Condo,8,False,4.944445,90,299,30.270900,-87.580321,2.0
1,2,Condo,4,False,5.000000,17,269,30.270686,-87.577590,2.5
2,2,Condo,6,False,4.636363,22,116,30.264288,-87.603913,2.0
3,3,Condo,6,False,4.958334,24,399,30.270686,-87.577590,3.0
4,2,Condo,8,False,4.789473,19,159,30.273040,-87.565347,2.0
...,...,...,...,...,...,...,...,...,...,...
345,3,Condo,8,False,4.680000,25,264,30.278852,-87.533716,3.0
346,4,Condo,10,False,4.837838,37,509,30.261642,-87.613446,2.0
347,3,House,6,True,4.926471,136,234,30.299086,-87.559069,2.0
348,3,Condo,12,False,4.560000,25,315,30.259116,-87.624228,4.0
349,1,Condo,6,False,4.920000,25,170,30.263593,-87.605253,2.0